(defsystem "woo-test"
  :depends-on ("woo"
               "clack-test"
               "lack-request"
               "rove")
  :components
  ((:file "t/woo")
   (:file "t/ipv6")
   (:file "t/file-size")
   (:file "t/worker")
   (:file "t/response")
   (:file "t/tls-stream" :if-feature (:not :woo-no-ssl))
   (:file "t/tlsretry" :if-feature (:not :woo-no-ssl))
   (:file "t/tlsreadretry" :if-feature (:not :woo-no-ssl))
   (:file "t/alpn" :if-feature (:not :woo-no-ssl))
   (:file "t/tls-context" :if-feature (:not :woo-no-ssl))
   (:file "t/response-validation")
   (:file "t/static")
   (:file "t/tls-static" :if-feature (:not :woo-no-ssl))
   (:file "t/upload")
   (:file "t/body-limit")
   (:file "t/hpack")
   (:file "t/http2-frames")
   (:file "t/http2-stream")
   (:file "t/http2-connection")
   (:file "t/http2-clack")
   (:file "t/http2-e2e")
   (:file "t/websocket")
   (:file "t/websocket-e2e"))
  :perform (test-op (op c) (unless (symbol-call '#:rove '#:run c)
               (error "Woo test gate failed"))))
