(in-package :woo.compat)

(defun adjust-output (connection delta reserve)
  (let* ((parent (parent-connection connection)) (server (connection-server parent))
         (request (and (not (connection-h2 parent)) (connection-request parent))))
    (bt2:with-lock-held ((ms-lock server))
      (when (or (not reserve)
                (and (<= (+ (ms-output-bytes server) delta) (ms-max-server-queue-bytes server))
                     (<= (+ (connection-output-bytes parent) delta) (ms-max-connection-queue-bytes server))
                     (or (null request)
                         (<= (+ (mr-output-bytes request) delta) (ms-max-response-queue-bytes server)))))
        (incf (ms-output-bytes server) delta)
        (incf (connection-output-bytes parent) delta)
        (when request (incf (mr-output-bytes request) delta))
        t))))

(defun install-h2-accounting (parent conn)
  (let ((server (connection-server parent)))
    (setf (woo.http2.connection::http2-connection-local-max-concurrent-streams conn)
          (ms-max-connection-requests server)
          (cdr (assoc woo.http2.constants:+settings-max-concurrent-streams+
                      (woo.http2.connection::http2-connection-local-settings conn)))
          (ms-max-connection-requests server))
    (setf (connection-h2 parent) conn
          (woo.http2.connection::http2-connection-budget-adjuster conn)
          (lambda (delta reserve) (adjust-output parent delta reserve))
          (woo.http2.connection::http2-connection-body-admitter conn)
          (lambda (stream count)
            (bt2:with-lock-held ((ms-lock server))
              (when (and (eq (ms-state server) :running)
                         (<= (+ (gethash stream (connection-h2-input parent) 0) count)
                             (ms-max-request-body-bytes server))
                         (<= (+ (ms-input-bytes server) count) (ms-max-request-storage-bytes server)))
                (incf (gethash stream (connection-h2-input parent) 0) count)
                (incf (ms-input-bytes server) count)
                t)))
          (woo.http2.connection::http2-connection-body-releaser conn)
          (lambda (stream ignored)
            (declare (ignore ignored))
            (bt2:with-lock-held ((ms-lock server))
              (decf (ms-input-bytes server) (gethash stream (connection-h2-input parent) 0))
              (remhash stream (connection-h2-input parent)))))
    (push (lambda ()
            (when (woo.http2.connection::http2-connection-cancel-responses conn)
              (funcall (woo.http2.connection::http2-connection-cancel-responses conn) nil))
            (bt2:with-lock-held ((ms-lock server))
              (maphash (lambda (stream n) (declare (ignore stream)) (decf (ms-input-bytes server) n))
                       (connection-h2-input parent))
              (clrhash (connection-h2-input parent))))
          (woo.ev.socket::socket-close-hooks (connection-socket parent)))))

(defun after-flush (connection thunk)
  (let ((socket (connection-socket connection)))
    (setf (woo.ev.socket::socket-flush-hooks socket)
          (nconc (woo.ev.socket::socket-flush-hooks socket) (list thunk)))
    (lev:ev-io-start woo.ev:*evloop* (woo.ev.socket:socket-write-watcher socket))))

(defun install-h2-completion (request)
  (let* ((conn (getf (mr-env request) :http2.connection))
         (previous (woo.http2.connection::http2-connection-stream-closed-hook conn)))
    ;; One connection callback searches its bounded active request set.
    (unless previous
      (setf (woo.http2.connection::http2-connection-stream-closed-hook conn)
            (lambda (stream)
              (let ((parent (parent-connection (mr-connection request))))
                (dolist (r (copy-list (connection-requests parent)))
                  (when (eq stream (mr-h2-stream r))
                    (if (eql (car (woo.http2.connection::http2-connection-last-rst conn))
                             (woo.http2.stream:http2-stream-id stream))
                        (cancel-request r)
                        (after-flush parent (lambda () (wire-completed r))))))))))))

(defun abandon-request (request)
  (ignore-errors
    (call-on-connection (mr-connection request)
      (lambda ()
        (if (mr-h2-stream request)
            (woo.http2.connection:connection-stream-error
             (getf (mr-env request) :http2.connection) (mr-h2-stream request)
             woo.http2.constants:+internal-error+)
            (woo.ev.socket:close-socket (connection-socket (mr-connection request)))))))
  (cancel-request request))

(defun response-headers (headers)
  (unless (and (listp headers) (evenp (length headers))) (error "Invalid response headers"))
  (let ((normalized
          (loop for (key value) on headers by #'cddr
                append (let ((name (string-downcase (string key))) (value (princ-to-string value)))
                         (unless (and (plusp (length name))
                                      (every (lambda (c) (and (< (char-code c) 128)
                                                             (or (alphanumericp c) (find c "!#$%&'*+-.^_`|~")))) name)
                                      (every (lambda (c) (and (<= (char-code c) 255)
                                                             (or (char= c #\Tab) (>= (char-code c) 32))
                                                             (/= (char-code c) 127))) value))
                           (error "Invalid response header"))
                         (list (intern (string-upcase name) :keyword) value)))))
    (when (> (count :content-length normalized) 1) (error "Repeated content length"))
    normalized))

(defun bytes-of (data &key (start 0) end)
  (woo.http2.clack::octets-of data :start start :end end))

(defun response-body-length (body)
  (etypecase body
    (null 0)
    (pathname (with-open-file (s body :element-type '(unsigned-byte 8)) (file-length s)))
    ((or string list (vector (unsigned-byte 8))) (woo.http2.clack::response-octet-length body))))

(defun wait-for-output (request)
  (let ((deadline (+ (now) (ms-cleanup-timeout (mr-server request)))))
    (loop
      (when (cancelled-p request) (error 'connection-closed))
      (when (call-on-connection (mr-connection request)
              (lambda ()
                (let ((socket (connection-socket (mr-connection request))))
                  (and (zerop (woo.ev.socket::socket-charged-output socket))
                       (or (null (mr-h2-stream request))
                           (let ((pending (gethash (woo.http2.stream:http2-stream-id (mr-h2-stream request))
                                                  (woo.http2.connection::http2-connection-send-queue
                                                   (getf (mr-env request) :http2.connection)))))
                             (or (null pending) (zerop (woo.http2.clack::pending-queued pending)))))))))
        (return t))
      (when (>= (now) deadline) (error 'connection-closed))
      (sleep 0.001))))

(defun emit-body (body writer &optional request)
  "Read ordinary bodies in bounded slices on the application worker."
  (labels ((part (data)
             (etypecase data
               (string
                (loop for start from 0 below (length data) by 4096
                      unless (funcall writer data :start start :end (min (length data) (+ start 4096)))
                        do (error 'connection-closed)
                      do (when request (wait-for-output request))))
               ((vector (unsigned-byte 8))
                (loop for start from 0 below (length data) by 16384
                      unless (funcall writer data :start start :end (min (length data) (+ start 16384)))
                        do (error 'connection-closed)
                      do (when request (wait-for-output request)))))))
    (etypecase body
      (null)
      (pathname
       (with-open-file (s body :element-type '(unsigned-byte 8))
         (let ((buffer (make-array 16384 :element-type '(unsigned-byte 8))))
           (loop for n = (read-sequence buffer s) while (plusp n)
                 unless (funcall writer buffer :end n) do (error 'connection-closed)
                 do (when request (wait-for-output request))))))
      (list (dolist (item body) (part item)))
      ((or string (vector (unsigned-byte 8))) (part body)))
    (funcall writer nil :close t)))

(defun finish-http1 (request)
  (let ((connection (mr-connection request)))
    (wire-completed request)
    (if (or (mr-close-p request) (not (eq (ms-state (mr-server request)) :running)))
        (woo.ev.socket:close-socket (connection-socket connection))
        (progn (setf (connection-request connection) nil) (resume-input connection)))))

(defun http1-responder (request response)
  (destructuring-bind (status headers) response
    (let* ((connection (mr-connection request)) (socket (connection-socket connection))
           (chunked (and (not (mr-bodyless request)) (null (mr-expected-length request))
                         (not (eq (getf (mr-env request) :server-protocol) :http/1.0)))))
      (setf (mr-chunked request) chunked)
      (let ((head (with-output-to-string (s)
                    (format s "HTTP/1.1 ~D ~A~C~C" status
                            (or (woo.response::status-code-to-text status) "Response") #\Return #\Linefeed)
                    (unless (getf headers :date)
                      (let ((woo.response::*date-header* (copy-seq "Thu, 01 Jan 1970 00:00:00 GMT")))
                        (format s "date: ~A~C~C" (woo.response::current-rfc-1123-timestamp) #\Return #\Linefeed)))
                    (loop for (k v) on headers by #'cddr
                          unless (member (string-downcase (string k)) '("connection" "transfer-encoding") :test #'equal)
                            do (format s "~A: ~A~C~C" (string-downcase (string k)) v #\Return #\Linefeed))
                    (when chunked (format s "transfer-encoding: chunked~C~C" #\Return #\Linefeed))
                    (when (mr-close-p request) (format s "connection: close~C~C" #\Return #\Linefeed))
                    (format s "~C~C" #\Return #\Linefeed))))
        (woo.ev.socket:write-socket-data socket (trivial-utf-8:string-to-utf-8-bytes head)))
      (lev:ev-io-start woo.ev:*evloop* (woo.ev.socket:socket-write-watcher socket))
      (lambda (octets &key close)
        (when (and octets (plusp (length octets)) (not (mr-bodyless request)))
          (if chunked (woo.response:write-body-chunk socket octets)
              (woo.ev.socket:write-socket-data socket octets)))
        (when close
          (when chunked (woo.ev.socket:write-socket-data socket woo.response:*empty-chunk*))
          (after-flush connection (lambda () (finish-http1 request))))
        (lev:ev-io-start woo.ev:*evloop* (woo.ev.socket:socket-write-watcher socket))
        t))))

(defun request-failed (request)
  (if (bt2:with-lock-held ((mr-lock request))
        (if (or (mr-headers-sent request) (mr-failure-handled request) (cancelled-p request))
            nil
            (setf (mr-failure-handled request) t)))
      (managed-responder request '(500 (:content-length 0) nil))
      (abandon-request request)))

(defun managed-responder (request response)
  (bt2:with-lock-held ((mr-lock request))
    (when (or (mr-headers-sent request) (cancelled-p request))
      (return-from managed-responder nil)))
  (handler-case
      (destructuring-bind (status headers &optional (body nil body-p)) response
        (check-type status (integer 200 599))
        (let* ((headers (response-headers headers))
               (bodyless (or (eq (getf (mr-env request) :request-method) :head)
                             (member status '(204 205 304))))
               (length-header (getf headers :content-length))
               (expected (and length-header (parse-integer length-header))))
          (when (string-equal (getf headers :connection) "close") (setf (mr-close-p request) t))
          (when (and expected (minusp expected)) (error "Negative content length"))
          (when (and body-p (not (member status '(204 205 304))))
            (let ((size (response-body-length body)))
              (when (and expected (/= size expected)) (error "Response length mismatch"))
              (setf expected size (getf headers :content-length) (write-to-string size))))
          (when (member status '(204 205))
            (remf headers :content-length) (setf expected nil))
          (bt2:with-lock-held ((mr-lock request))
            (when (or (mr-headers-sent request) (cancelled-p request))
              (return-from managed-responder nil))
            (setf (mr-headers-sent request) t (mr-bodyless request) bodyless
                  (mr-expected-length request) expected (mr-status request) status))
          (let* ((connection (mr-connection request))
                 (downstream (call-on-connection connection
                               (lambda () (funcall (mr-responder request) (list status headers)))))
                 (writer
                   (lambda (data &key (start 0) end close)
                    (block write-chunk
                     (handler-case
                     (bt2:with-lock-held ((mr-lock request))
                       (when (or (mr-writer-closed request) (cancelled-p request))
                         (return-from write-chunk nil))
                       (let* ((n (if bodyless 0 (woo.http2.clack::response-octet-length data :start start :end end)))
                              (total (+ (mr-delivered-bytes request) n)))
                         (when (and (not bodyless) expected
                                    (or (> total expected) (and close (/= total expected))))
                           (error "Response length mismatch"))
                         (when close (setf (mr-writer-closed request) t))
                         (unless (adjust-output connection n t) (error 'queue-limit-exceeded))
                         (let ((ok (unwind-protect
                                     (call-on-connection connection
                                       (lambda ()
                                         (let ((accepted
                                                 (if (mr-h2-stream request)
                                                     (funcall downstream (if bodyless nil data) :start start :end end :close close)
                                                     (funcall downstream (if bodyless nil (bytes-of data :start start :end end)) :close close))))
                                           (when accepted (setf (mr-delivered-bytes request) total))
                                           accepted)))
                                     (adjust-output connection (- n) nil))))
                           ok)))
                       (error () (abandon-request request) nil))))))
            (if body-p (progn (unless bodyless (emit-body body writer request))
                             (when bodyless (funcall writer nil :close t)) nil)
                writer))))
    (error () (request-failed request) nil)))

;; The raw socket API is available only on HTTP/1, and every operation runs on
;; its owner loop. A stream proxy cannot accidentally corrupt an HTTP/2 socket.
(defun raw-connection (connection)
  (when (typep connection 'stream-connection) (error "HTTP/2 does not support raw socket takeover"))
  connection)
(defmethod clack.socket:read-callback ((c connection))
  (call-on-connection (raw-connection c) (lambda () (woo.ev.socket:socket-data (connection-socket c)))))
(defmethod (setf clack.socket:read-callback) (callback (c connection))
  (call-on-connection (raw-connection c)
    (lambda () (setf (connection-upgraded c) t
                     (woo.ev.socket:socket-data (connection-socket c)) callback)))
  callback)
(defmethod clack.socket:write-sequence-to-socket-buffer ((c connection) data)
  (call-on-connection (raw-connection c)
    (lambda () (woo.ev.socket:write-socket-data (connection-socket c) data))))
(defmethod clack.socket:write-byte-to-socket-buffer ((c connection) byte)
  (clack.socket:write-sequence-to-socket-buffer c (make-array 1 :element-type '(unsigned-byte 8) :initial-element byte)))
(defmethod clack.socket:flush-socket-buffer ((c connection) &key callback)
  (call-on-connection (raw-connection c)
    (lambda ()
      (after-flush c
        (lambda ()
          (when (connection-upgraded c)
            (wire-completed (connection-request c))
            (resume-input c))
          (when callback (funcall callback)))))))
(defmethod clack.socket:write-sequence-to-socket ((c connection) data &key callback)
  (clack.socket:write-sequence-to-socket-buffer c data)
  (clack.socket:flush-socket-buffer c :callback callback))
(defmethod clack.socket:write-byte-to-socket ((c connection) byte &key callback)
  (clack.socket:write-byte-to-socket-buffer c byte)
  (clack.socket:flush-socket-buffer c :callback callback))
(defmethod clack.socket:close-socket ((c connection))
  (if (typep c 'stream-connection)
      (abandon-request (connection-request c))
      (call-on-connection c (lambda () (woo.ev.socket:close-socket (connection-socket c))))))
(defmethod clack.socket:socket-async-p ((c connection)) t)
