(in-package :woo.compat)

(defun map-response (app env transform)
  (let ((response (funcall app env)))
    (if (functionp response)
        (lambda (respond)
          (funcall response (lambda (r) (funcall respond (funcall transform r)))))
        (funcall transform response))))

(defun request-cancelled (env)
  (let ((predicate (getf env :woo.request-cancelled-p))) (and predicate (funcall predicate))))

(defun wrap-mount (app path mounted-app)
  (check-type path string)
  (let ((mounted-app (lack.component:to-app mounted-app)))
    (lambda (env)
      (let ((info (getf env :path-info)) (len (length path)))
        (if (and (<= len (length info)) (string= path info :end2 len)
                 (or (= len (length info)) (char= (char info len) #\/)))
            (let ((child (copy-list env)))
              (setf (getf child :script-name) (concatenate 'string (getf env :script-name) path)
                    (getf child :path-info) (if (= len (length info)) "/" (subseq info len)))
              (funcall mounted-app child))
            (funcall app env))))))

(defun wrap-accesslog (app &key (logger (lambda (entry) (format *standard-output* "~S~%" entry))))
  "Log completion metadata. Paths, query strings, headers and bodies are omitted."
  (lambda (env)
    (let ((request (getf env :woo.request)) (start (now)))
      (unless request (error "WOO-ACCESSLOG requires the managed profile"))
      (on-completion request
          (lambda (r)
                  (let ((entry (list :method (getf env :request-method) :status (mr-status r)
                                     :accepted-body-bytes (mr-delivered-bytes r)
                                     :cancelled (mr-cancelled r) :elapsed (- (now) start)))
                        (server (mr-server r)))
                    (bt2:with-lock-held ((ms-lock server))
                      (if (and (member (ms-state server) '(:running :draining))
                               (< (length (ms-jobs server)) (ms-max-pending-requests server)))
                          (progn (setf (ms-jobs server)
                                       (nconc (ms-jobs server) (list (lambda () (ignore-errors (funcall logger entry))))))
                                 (bt2:condition-notify (ms-wake server)))
                          (incf (ms-dropped-completions server)))))))
      (funcall app env))))

(defun wrap-backtrace (app &key (logger (lambda (entry) (format *error-output* "~S~%" entry))))
  "Report error types without printing conditions or request secrets."
  (lambda (env)
    (labels ((failed (condition)
               (funcall logger (list :error-type (type-of condition)))
               (let ((request (getf env :woo.request)))
                 (if (and request (or (mr-headers-sent request) (cancelled-p request)))
                     (progn (request-failed request) nil)
                     '(500 (:content-type "text/plain") ("Internal Server Error"))))))
      (handler-case
          (let ((response (funcall app env)))
            (if (functionp response)
                (lambda (respond)
                  (handler-case (funcall response respond)
                    (error (c) (let ((fallback (failed c)))
                                 (when fallback (funcall respond fallback))))))
                response))
        (error (c) (failed c))))))

(defun encoding-quality (header encoding)
  (let ((explicit nil) (wildcard nil))
    (dolist (item (uiop:split-string (or header "") :separator '(#\,)))
      (let* ((parts (uiop:split-string item :separator '(#\;)))
             (name (string-downcase (string-trim '(#\Space #\Tab) (first parts))))
             (quality 1))
        (dolist (parameter (rest parts))
          (let ((p (string-downcase (string-trim '(#\Space #\Tab) parameter))))
            (when (and (>= (length p) 2) (string= p "q=" :end1 2))
              ;; Decimal parsing avoids READ and reader macros from HTTP input.
              (let ((digits (subseq p 2)))
                (setf quality
                      (if (and (<= (length digits) 5) (plusp (length digits))
                               (member (char digits 0) '(#\0 #\1))
                               (or (= (length digits) 1)
                                   (and (char= (char digits 1) #\.)
                                        (every #'digit-char-p (subseq digits 2))))
                               (or (= (length digits) 1) (char= (char digits 0) #\0)
                                   (every (lambda (c) (char= c #\0)) (subseq digits 2))))
                          (+ (digit-char-p (char digits 0))
                             (if (> (length digits) 2)
                                 (/ (parse-integer digits :start 2) (expt 10 (- (length digits) 2))) 0))
                          0))))))
        (cond ((string= name encoding) (setf explicit quality))
              ((string= name "*") (setf wildcard quality)))))
    (or explicit wildcard 0)))

(defclass compression-output (trivial-gray-streams:fundamental-binary-output-stream)
  ((writer :initarg :writer :reader compression-output-writer)
   (discard :initform nil :accessor compression-output-discard)
   (closing :initform nil :accessor compression-output-closing)
   (failed :initform nil :accessor compression-output-failed)))
(defmethod stream-element-type ((s compression-output)) '(unsigned-byte 8))
(defmethod trivial-gray-streams:stream-write-sequence ((s compression-output) seq start end &key)
  (unless (compression-output-discard s)
    (handler-case
        (unless (funcall (compression-output-writer s) seq :start start :end end)
          (error 'connection-closed))
      (error (condition)
        (if (compression-output-closing s)
            ;; Finish the compressor so its native resources can be freed.
            (setf (compression-output-discard s) t (compression-output-failed s) t)
            (error condition)))))
  seq)
(defmethod trivial-gray-streams:stream-write-byte ((s compression-output) byte)
  (write-sequence (make-array 1 :element-type '(unsigned-byte 8) :initial-element byte) s) byte)
(defmethod trivial-gray-streams:stream-finish-output ((s compression-output)) nil)

(defun compression-writer (writer algorithm env)
  (let* ((output (make-instance 'compression-output :writer writer))
         (stream (if (string= algorithm "gzip")
                     (salza2:make-compressing-stream 'salza2:gzip-compressor output)
                     (zstd:make-compressing-stream output)))
         (lock (bt2:make-lock)) (closed nil))
    (lambda (data &key (start 0) end close)
      (block write-compressed
      (bt2:with-lock-held (lock)
        (when closed (return-from write-compressed nil))
        (handler-case
            (progn
              (when (request-cancelled env) (error 'connection-closed))
              (when data
                (if (stringp data)
                    (loop for offset from start below (or end (length data)) by 4096
                          do (write-sequence (bytes-of data :start offset :end (min (or end (length data)) (+ offset 4096))) stream))
                    (write-sequence data stream :start start :end end)))
              (when close
                (setf closed t (compression-output-closing output) t)
                (close stream)
                (setf stream nil)
                (when (compression-output-failed output) (return-from write-compressed nil))
                (unless (funcall writer nil :close t) (return-from write-compressed nil)))
              t)
          (error ()
            (setf closed t (compression-output-discard output) t)
            (when stream (ignore-errors (close stream :abort t)))
            nil)))))))

(defun wrap-deflater (app &key content-type)
  (lambda (env)
    (let* ((accept (gethash "accept-encoding" (getf env :headers)))
           (gzip (encoding-quality accept "gzip")) (zstd (encoding-quality accept "zstd"))
           (algorithm (cond ((and (> zstd 0) (>= zstd gzip)) "zstd") ((> gzip 0) "gzip"))))
      (labels ((eligible (r)
                 (and algorithm (not (eq (getf env :request-method) :head))
                      (not (member (first r) '(204 205 304)))
                      (not (getf (second r) :content-encoding))
                      (not (getf (second r) :content-range))
                      (or (null content-type)
                          (let ((type (getf (second r) :content-type)))
                            (and type (some (lambda (prefix) (uiop:string-prefix-p prefix type))
                                            (if (listp content-type) content-type (list content-type))))))))
               (respond-compressed (r respond)
                 (if (not (eligible r)) (funcall respond r)
                     (destructuring-bind (status headers &optional (body nil body-p)) r
                       (let ((headers (copy-list headers)))
                         (remf headers :content-length)
                         (setf (getf headers :content-encoding) algorithm
                               (getf headers :vary) (if (getf headers :vary)
                                                       (format nil "~A, Accept-Encoding" (getf headers :vary)) "Accept-Encoding"))
                         (let ((writer (compression-writer (funcall respond (list status headers)) algorithm env)))
                           (if body-p (progn (emit-body body writer) nil) writer)))))))
        (let ((r (funcall app env)))
          (if (functionp r)
              (lambda (respond) (funcall r (lambda (response) (respond-compressed response respond))))
              (if (eligible r) (lambda (respond) (respond-compressed r respond)) r)))))))

;; Striped locks have a fixed footprint. Different SIDs may serialize when they
;; hash to the same stripe. Locks are owned by a lease, never by a thread: a
;; delayed responder may finish on another thread.
(defstruct session-stripe busy)
(defstruct session-coordinator
  (lock (bt2:make-lock)) (cv (bt2:make-condition-variable))
  (store-lock (bt2:make-lock))
  (stripes (map 'vector (lambda (x) (declare (ignore x)) (make-session-stripe)) (make-list 256))))
(defvar *session-coordinators-lock* (bt2:make-lock))
(defvar *session-coordinators*
  #+sbcl (make-hash-table :test 'eq :weakness :key)
  #-sbcl (make-hash-table :test 'eq))
(defun store-coordinator (store)
  (let* ((package (find-package :lack.session.store.redis))
         (redis-type (and package (find-symbol "REDIS-STORE" package)))
         (key (if (and redis-type (typep store redis-type))
                  (funcall (find-symbol "REDIS-STORE-CONNECTION" package) store) store)))
    (bt2:with-lock-held (*session-coordinators-lock*)
      (or (gethash key *session-coordinators*)
          (setf (gethash key *session-coordinators*) (make-session-coordinator))))))
(defun wrap-session (app &key
                           (store (lack.middleware.session.store.memory:make-memory-store))
                           (state (lack.middleware.session.state.cookie:make-cookie-state))
                           (keep-empty t) (lock-timeout 10))
  (let* ((coordinator (store-coordinator store))
         (stripes (session-coordinator-stripes coordinator)) (lock (session-coordinator-lock coordinator))
         (cv (session-coordinator-cv coordinator)) (store-lock (session-coordinator-store-lock coordinator)))
    (lambda (env)
      (block session-request
      (let* ((sid (or (lack.session.state:extract-sid state env) (lack.session.state:generate-sid state env)))
             (stripe (aref stripes (mod (sxhash sid) (length stripes))))
             (released nil) (finalized nil) (final-lock (bt2:make-lock))
             (deadline (+ (now) lock-timeout)))
        (labels ((release ()
                   (bt2:with-lock-held (lock)
                     (unless released
                       (setf released t (session-stripe-busy stripe) nil)
                       (bt2:condition-notify cv))))
                 (finalize (r)
                   (bt2:with-lock-held (final-lock)
                     (when finalized (error "Session responder called twice"))
                     (setf finalized t)
                     (unwind-protect
                          (if (request-cancelled env) r
                              (bt2:with-lock-held (store-lock)
                                (let ((*read-eval* nil))
                                (handler-bind ((warning #'muffle-warning))
                                  (if (and (not keep-empty)
                                           (getf (getf env :lack.session.options) :new-session)
                                           (zerop (hash-table-count (getf env :lack.session)))) r
                                      (lack.middleware.session::finalize store state env r))))))
                       (release)))))
          (bt2:with-lock-held (lock)
            (loop while (session-stripe-busy stripe)
                  do (when (or (request-cancelled env) (>= (now) deadline))
                       (return-from session-request '(503 (:content-type "text/plain") ("Session busy"))))
                     (bt2:condition-wait cv lock :timeout 0.05))
            (setf (session-stripe-busy stripe) t))
          (handler-case
              (let* ((session (bt2:with-lock-held (store-lock)
                                (let ((*read-eval* nil))
                                (handler-bind ((warning #'muffle-warning)) (lack.session.store:fetch-session store sid)))))
                     (new (null session)))
                (setf (getf env :lack.session) (if session (alexandria:copy-hash-table session) (make-hash-table :test 'equal))
                      (getf env :lack.session.options) (list :id sid :new-session new :change-id nil :expire nil))
                (when (getf env :woo.request)
                  (let ((request (getf env :woo.request)))
                    (on-completion request (lambda (r) (declare (ignore r)) (release)))))
                (let ((r (funcall app env)))
                  (if (functionp r)
                      (lambda (respond)
                        (handler-case (funcall r (lambda (res) (funcall respond (finalize res))))
                          (error (c) (release) (error c))))
                      (finalize r))))
            (error (c) (release) (error c)))))))))

(defpackage lack/middleware/woo-mount (:use :cl) (:export :*lack-middleware-woo-mount*))
(in-package :lack/middleware/woo-mount)
(defparameter *lack-middleware-woo-mount* #'woo.compat::wrap-mount)
(defpackage lack/middleware/woo-accesslog (:use :cl) (:export :*lack-middleware-woo-accesslog*))
(in-package :lack/middleware/woo-accesslog)
(defparameter *lack-middleware-woo-accesslog* #'woo.compat::wrap-accesslog)
(defpackage lack/middleware/woo-backtrace (:use :cl) (:export :*lack-middleware-woo-backtrace*))
(in-package :lack/middleware/woo-backtrace)
(defparameter *lack-middleware-woo-backtrace* #'woo.compat::wrap-backtrace)
(defpackage lack/middleware/woo-deflater (:use :cl) (:export :*lack-middleware-woo-deflater*))
(in-package :lack/middleware/woo-deflater)
(defparameter *lack-middleware-woo-deflater* #'woo.compat::wrap-deflater)
(defpackage lack/middleware/woo-session (:use :cl) (:export :*lack-middleware-woo-session*))
(in-package :lack/middleware/woo-session)
(defparameter *lack-middleware-woo-session* #'woo.compat::wrap-session)
