(in-package :woo.compat)

(defun call-on-connection (connection thunk)
  "Execute THUNK on CONNECTION's loop and return its values. Late calls fail.
Do not wait for an application worker from inside THUNK."
  (check-type connection connection)
  (if (eq (bt2:current-thread) (connection-owner connection))
      (progn
        (unless (woo.ev.socket:socket-open-p (connection-socket connection))
          (error 'connection-closed))
        (funcall thunk))
      (let ((done (bt2:make-semaphore :count 0)) (values nil) (failure nil)
            (lock (bt2:make-lock)) (state :pending)
            (deadline (+ (now) (ms-cleanup-timeout (connection-server connection)))))
        (labels ((dropped ()
                   (bt2:with-lock-held (lock)
                     (setf state :done failure (make-condition 'connection-closed)))
                   (bt2:signal-semaphore done))
                 (execute ()
                   ;; A timeout must not leave a queued write that can run later.
                   (when (bt2:with-lock-held (lock)
                           (when (eq state :pending) (setf state :running)))
                     (unwind-protect
                          (handler-case
                              (if (woo.ev.socket:socket-open-p (connection-socket connection))
                                  (setf values (multiple-value-list (funcall thunk)))
                                  (setf failure (make-condition 'connection-closed)))
                            (error (c) (setf failure c)))
                       (bt2:with-lock-held (lock) (setf state :done))
                       (bt2:signal-semaphore done)))))
          (let ((woo.dispatch:*dispatch-drop-callback* #'dropped))
            (unless (funcall (connection-runner connection) #'execute)
              (error 'connection-closed)))
          (loop until (bt2:wait-on-semaphore done :timeout 0.1)
                when (or (>= (now) deadline)
                         (not (woo.ev.socket:socket-open-p (connection-socket connection))))
                  do (bt2:with-lock-held (lock)
                       (when (eq state :pending) (setf state :abandoned)))
                     (error 'connection-closed))
          (when failure (error failure))
          (values-list values)))))

(defun on-completion (request callback)
  "Register exactly once, including a completion racing with registration."
  (when (bt2:with-lock-held ((ms-lock (mr-server request)))
          (if (mr-wire-done request) t (progn (push callback (mr-callbacks request)) nil)))
    (funcall callback request)))

(defun maybe-release-request (request)
  (let ((server (mr-server request)))
    (bt2:with-lock-held ((ms-lock server))
      (when (and (mr-producer-done request) (mr-wire-done request)
                 (not (eq (mr-phase request) :closed)))
        (when (mr-body request)
          (unwind-protect
               (ignore-errors (close (mr-body request)))
            (ignore-errors (smart-buffer:delete-stream-file (mr-body request)))))
        (setf (mr-phase request) :closed (mr-body request) nil (mr-env request) nil)
        (decf (ms-input-bytes server) (mr-input-bytes request))
        (setf (mr-input-bytes request) 0)
        (remhash request (ms-requests server))
        (setf (connection-requests (parent-connection (mr-connection request)))
              (remove request (connection-requests (parent-connection (mr-connection request)))))
        (bt2:condition-notify (ms-wake server))))))

(defun wire-completed (request &optional cancelled)
  (let ((callbacks nil) (server (mr-server request)))
    (bt2:with-lock-held ((ms-lock server))
      (when cancelled (setf (mr-cancelled request) t))
      (unless (mr-wire-done request)
        (setf (mr-wire-done request) t callbacks (mr-callbacks request)
              (mr-callbacks request) nil)))
    (dolist (callback callbacks)
      (handler-case (funcall callback request) (error () nil)))
    (maybe-release-request request)))

(defun cancel-request (request)
  (wire-completed request t))

(defun pool-worker (server)
  (let ((*random-state* (make-random-state t)))
   (loop
    (let ((job
            (bt2:with-lock-held ((ms-lock server))
              (loop while (and (null (ms-jobs server))
                               (member (ms-state server) '(:starting :running :draining)))
                    do (bt2:condition-wait (ms-wake server) (ms-lock server) :timeout 0.1))
              (when (null (ms-jobs server)) (return-from pool-worker nil))
              (incf (ms-running server))
              (pop (ms-jobs server)))))
      (unwind-protect (funcall job)
        (bt2:with-lock-held ((ms-lock server))
          (decf (ms-running server))
          (bt2:condition-notify (ms-wake server))))))))

(defun submit-request (request thunk)
  (let ((server (mr-server request)))
    (bt2:with-lock-held ((ms-lock server))
      (when (and (eq (ms-state server) :running)
                 (< (length (ms-jobs server)) (ms-max-pending-requests server))
                 (<= (length (connection-requests (parent-connection (mr-connection request))))
                     (ms-max-connection-requests server)))
        (setf (ms-jobs server) (nconc (ms-jobs server) (list thunk)))
        (bt2:condition-notify (ms-wake server))
        t))))

(defun admit-input (connection count)
  (let ((server (connection-server connection)))
    (bt2:with-lock-held ((ms-lock server))
      (when (and (eq (ms-state server) :running)
                 (<= (+ (connection-input-bytes connection) count) (ms-max-request-body-bytes server))
                 (<= (+ (ms-input-bytes server) count) (ms-max-request-storage-bytes server)))
        (incf (connection-input-bytes connection) count)
        (incf (ms-input-bytes server) count)
        t))))

(defun hold-input (connection data start end)
  (let* ((n (- end start)) (server (connection-server connection))
         (admitted (bt2:with-lock-held ((ms-lock server))
                     (when (and (<= (+ (connection-held-bytes connection) n) (ms-max-request-body-bytes server))
                                (<= (+ (ms-input-bytes server) n) (ms-max-request-storage-bytes server)))
                       (incf (connection-held-bytes connection) n)
                       (incf (ms-input-bytes server) n)
                       t))))
    (if admitted (push (subseq data start end) (connection-held connection))
        (woo.ev.socket:close-socket (connection-socket connection)))))

(defun resume-input (connection)
  (let ((socket (connection-socket connection)) (server (connection-server connection))
        (held (nreverse (connection-held connection))))
    (setf (connection-held connection) nil)
    (bt2:with-lock-held ((ms-lock server))
      (decf (ms-input-bytes server) (connection-held-bytes connection))
      (setf (connection-held-bytes connection) 0))
    (when (woo.ev.socket:socket-open-p socket)
      (setf (woo.ev.socket::socket-input-paused-p socket) nil)
      (lev:ev-io-start woo.ev:*evloop* (woo.ev.socket:socket-read-watcher socket))
      (dolist (data held)
        (if (woo.ev.socket::socket-input-paused-p socket)
            (hold-input connection data 0 (length data))
            (funcall (woo.ev.socket:socket-read-cb socket) socket data :start 0 :end (length data)))))))

(defun install-connection (server socket)
  (let ((connection (make-instance 'connection :server server :socket socket
                                   :owner (bt2:current-thread)
                                   :runner (woo.dispatch:make-loop-runner socket))))
    (bt2:with-lock-held ((ms-lock server))
      (setf (gethash socket (ms-connections server)) connection))
    (setf (woo.ev.socket::socket-output-admitter socket)
          (lambda (n) (adjust-output connection n t))
          (woo.ev.socket::socket-output-releaser socket)
          (lambda (n) (adjust-output connection (- n) nil))
          (woo.ev.socket::socket-http2-initializer socket)
          (lambda (conn) (install-h2-accounting connection conn)))
    (setf (woo.ev.socket::socket-body-memory-limit socket) (ms-max-request-body-bytes server))
    (setf (woo.ev.socket::socket-body-admitter socket)
          (lambda (count) (admit-input connection count))
          (woo.ev.socket::socket-input-holder socket)
          (lambda (data start end) (hold-input connection data start end)))
    (push
     (lambda ()
       (dolist (request (copy-list (connection-requests connection))) (cancel-request request))
       (bt2:with-lock-held ((ms-lock server))
         (decf (ms-input-bytes server) (+ (connection-input-bytes connection)
                                        (connection-held-bytes connection)))
         (setf (connection-input-bytes connection) 0 (connection-held-bytes connection) 0
               (connection-held connection) nil)
         (remhash socket (ms-connections server))))
     (woo.ev.socket::socket-close-hooks socket))
    connection))

(defun managed-application (server env)
  ;; Called on the network loop. The application itself runs in POOL-WORKER.
  (let* ((socket (getf env :clack.io))
         (parent (bt2:with-lock-held ((ms-lock server)) (gethash socket (ms-connections server))))
         (h2 (getf env :http2.stream))
         (connection (if h2 (make-instance 'stream-connection :parent parent :server server
                                           :socket socket :runner (connection-runner parent)
                                           :owner (connection-owner parent)) parent))
         (request (make-managed-request :server server :connection connection :env env
                                        :body (getf env :raw-body) :h2-stream h2
                                        :runner (connection-runner parent))))
    (nconc env (list :woo.request-cancelled-p nil :woo.request nil))
    (setf (getf env :url-scheme) (if (woo.ev.socket:socket-ssl-handle socket) "https" "http"))
    (unless h2
      (multiple-value-bind (name explicit-port)
          (let ((host (gethash "host" (getf env :headers))))
            (if (stringp host) (woo::parse-host-header host) (values nil nil)))
        (declare (ignore name))
        (unless explicit-port
          (setf (getf env :server-port) (if (woo.ev.socket:socket-ssl-handle socket) 443 80)))))
    (setf (getf env :headers) (alexandria:copy-hash-table (getf env :headers)))
    (setf (getf env :clack.io) connection
          (getf env :woo.request-cancelled-p) (lambda () (cancelled-p request))
          (getf env :woo.request) request)
    (setf (connection-request connection) request)
    (unless h2
      (setf (mr-input-bytes request) (connection-input-bytes parent)
            (connection-input-bytes parent) 0
            (woo.ev.socket::socket-input-paused-p socket) t)
      ;; Keep the watcher active to observe EOF while the HTTP parser is
      ;; paused. Extra input is copied only after bounded admission.
      (setf (getf env :woo.response-handler)
            (lambda (http ignored response)
              (declare (ignore http ignored))
              (setf (mr-close-p request)
                    (or (eq (getf env :server-protocol) :http/1.0)
                        (string-equal (gethash "connection" (getf env :headers)) "close")))
              (funcall response (lambda (res) (http1-responder request res))))))
    (when h2
      (setf (connection-h2 parent) (getf env :http2.connection))
      (let ((bytes (gethash h2 (connection-h2-input parent) 0)))
        (setf (mr-input-bytes request) bytes)
        (remhash h2 (connection-h2-input parent)))
      (install-h2-completion request))
    (bt2:with-lock-held ((ms-lock server))
      (push request (connection-requests parent))
      (setf (gethash request (ms-requests server)) t))
    (lambda (responder)
      (setf (mr-responder request) responder)
      (unless
          (and (not (mr-cancelled request))
               (submit-request
                request
                (lambda ()
                  (unwind-protect
                       (handler-case
                           (unless (cancelled-p request)
                             (let* ((result (funcall (ms-app server) env))
                                    (respond (lambda (res) (managed-responder request res))))
                               (etypecase result
                                 (list (unless (connection-upgraded parent) (funcall respond result)))
                                 (function (funcall result respond)))))
                         (error () (request-failed request)))
                    (setf (mr-producer-done request) t)
                    (maybe-release-request request)))))
        (setf (mr-producer-done request) t)
        (managed-responder request '(503 (:content-length 0) nil))
        (maybe-release-request request)))))

(defun start-managed (app &rest options &key (use-thread nil)
                         (application-workers 4) (max-pending-requests 64)
                         (max-connection-requests 16) (max-request-body-bytes (* 64 1024 1024))
                         (max-request-storage-bytes (* 256 1024 1024))
                         (max-response-queue-bytes (* 8 1024 1024))
                         (max-connection-queue-bytes (* 64 1024 1024))
                         (max-server-queue-bytes (* 256 1024 1024))
                         (startup-timeout 10) (drain-timeout 10) (cleanup-timeout 5)
                         &allow-other-keys)
  (when (getf options :worker-num) (error "Managed profile uses one network loop; omit :worker-num"))
  (when use-thread (error "Use WOO.COMPAT:CLACKUP; outer Clack threading is unsupported"))
  (dolist (value (list application-workers max-pending-requests max-connection-requests
                       max-request-body-bytes max-request-storage-bytes max-response-queue-bytes
                       max-connection-queue-bytes max-server-queue-bytes))
    (check-type value (integer 1 *)))
  (dolist (value (list startup-timeout drain-timeout cleanup-timeout))
    (check-type value (real (0) *)))
  (let* ((server (make-managed-server :app app :application-workers application-workers
                    :max-pending-requests max-pending-requests :max-connection-requests max-connection-requests
                    :max-request-body-bytes max-request-body-bytes :max-request-storage-bytes max-request-storage-bytes
                    :max-response-queue-bytes max-response-queue-bytes :max-connection-queue-bytes max-connection-queue-bytes
                    :max-server-queue-bytes max-server-queue-bytes :startup-timeout startup-timeout
                    :drain-timeout drain-timeout :cleanup-timeout cleanup-timeout))
         (woo-options (copy-list options)))
    (dolist (key '(:application-workers :max-pending-requests :max-connection-requests
                   :max-request-body-bytes :max-request-storage-bytes :max-response-queue-bytes
                   :max-connection-queue-bytes :max-server-queue-bytes :startup-timeout
                   :drain-timeout :cleanup-timeout :use-thread :allow-other-keys))
      (remf woo-options key))
    (handler-case
        (progn
          (dotimes (i application-workers)
            (push (bt2:make-thread (lambda () (pool-worker server)) :name "Woo application worker")
                  (ms-workers server)))
          (setf (ms-thread server)
                (bt2:make-thread
                 (lambda ()
                   (let (#-woo-no-ssl (woo.ssl:*alpn-protocols* '("h2" "http/1.1"))
                         (woo.http2.clack::*max-queued-response-bytes* (ms-max-response-queue-bytes server))
                         (woo.http2.clack::*max-connection-queued-response-bytes* (ms-max-connection-queue-bytes server))
                         (woo.http2.connection::*max-request-body-size* (ms-max-request-body-bytes server)))
                     (handler-case
                         (apply #'woo:run (lambda (env) (managed-application server env))
                                :on-connection (lambda (socket) (install-connection server socket))
                                :on-ready (lambda (control)
                                            (bt2:with-lock-held ((ms-lock server))
                                              (setf (ms-control server) control)
                                              (if (eq (ms-state server) :starting)
                                                  (setf (ms-state server) :running)
                                                  (woo:stop-gracefully (bt2:current-thread)))))
                                :handle-signals nil :allow-other-keys t woo-options)
                       (error (c)
                         (bt2:with-lock-held ((ms-lock server))
                           (setf (ms-startup-error server) c (ms-state server) :failed))))))
                 :name "Woo managed network")))
      (error (condition)
        (bt2:with-lock-held ((ms-lock server)) (setf (ms-state server) :failed))
        (stop-managed server)
        (error condition)))
    (let ((deadline (+ (now) startup-timeout)))
      (loop while (and (eq (ms-state server) :starting) (< (now) deadline)) do (sleep 0.01)))
    (unless (eq (ms-state server) :running)
      (stop-managed server)
      (if (ms-startup-error server) (error (ms-startup-error server))
          (error "Managed Woo startup exceeded its deadline")))
    server))

(defun stop-managed (server)
  (check-type server managed-server)
  (when (eq (ms-state server) :stopped) (return-from stop-managed t))
  (let ((drain-deadline (+ (now) (ms-drain-timeout server))))
    (setf (ms-drain-deadline server) drain-deadline)
    (bt2:with-lock-held ((ms-lock server)) (setf (ms-state server) :draining))
    (when (ms-thread server) (woo::quiesce (ms-thread server)))
    (let* ((connections (bt2:with-lock-held ((ms-lock server))
                          (loop for c being the hash-values of (ms-connections server) collect c)))
           (owner (find-if (lambda (c) (woo.ev.socket:socket-open-p (connection-socket c))) connections)))
      ;; One dispatch bounds the control wait independently of connection count.
      (when owner
        (ignore-errors
          (call-on-connection owner
            (lambda ()
              (dolist (connection connections)
                (when (woo.ev.socket:socket-open-p (connection-socket connection))
                  (when (connection-h2 connection)
                    (setf (woo.http2.connection::http2-connection-draining (connection-h2 connection)) t)
                    (woo.http2.connection:connection-send-frame
                     (connection-h2 connection)
                     (woo.http2.frames:make-goaway-frame
                      (woo.http2.connection::http2-connection-last-stream-id (connection-h2 connection)) 0)))
                  (when (null (connection-requests connection))
                    (woo.ev.socket:graceful-close-socket
                     (connection-socket connection)
                     :deadline (+ (lev:ev-now woo.ev:*evloop*)
                                  (max 0.0d0 (- drain-deadline (now)))))))))))))
    (loop while (and (< (now) drain-deadline)
                     (bt2:with-lock-held ((ms-lock server))
                       (plusp (hash-table-count (ms-requests server))))) do (sleep 0.01)))
  (bt2:with-lock-held ((ms-lock server)) (setf (ms-state server) :stopping))
  (when (ms-thread server) (woo:stop-gracefully (ms-thread server)))
  (let* ((threads (remove nil (cons (ms-thread server) (ms-workers server))))
         (deadline (+ (now) (ms-cleanup-timeout server))))
    (loop while (and (< (now) deadline) (some #'bt2:thread-alive-p threads)) do (sleep 0.01))
    (let ((live (remove-if-not #'bt2:thread-alive-p threads)))
      (when live (error 'shutdown-timeout :workers live)))
    (dolist (thread threads) (bt2:join-thread thread)))
  (setf (ms-state server) :stopped)
  t)

(defun clackup (app &rest options &key (server :woo-managed) (use-thread nil)
                           (debug nil) (use-default-middlewares nil) &allow-other-keys)
  "Start the managed profile, returning an ordinary Clack handler."
  (unless (eq server :woo-managed) (error "Managed profile requires :server :woo-managed"))
  (when use-thread (error "Managed profile owns its threads; :use-thread must be NIL"))
  (when use-default-middlewares (error "Select explicit middleware for the managed profile"))
  (dolist (key '(:server :use-thread :debug :use-default-middlewares)) (remf options key))
  (apply #'clack:clackup app :server :woo-managed :use-thread nil :debug debug
         :use-default-middlewares nil options))

(in-package :clack.handler.woo-managed)
(defun run (app &rest options &key &allow-other-keys)
  (apply #'woo.compat::start-managed app options))
(defun stop (server) (woo.compat::stop-managed server))
