(in-package :woo.compat.tests)
(deftest explicit-mount-preserves-parent
  (let* ((original (env)) (seen nil)
         (app (lack:builder
                (:woo-mount "/api" (lambda (e) (setf seen e) '(200 nil ("mounted"))))
                (lambda (e) (declare (ignore e)) '(404 nil nil)))))
    (setf (getf original :path-info) "/api/item")
    (ok (= (car (funcall app original)) 200))
    (ok (string= (getf original :path-info) "/api/item"))
    (ok (string= (getf seen :script-name) "/api")) (ok (string= (getf seen :path-info) "/item"))))

(deftest deflater-qualities-and-delayed-body
  (ok (= (woo.compat::encoding-quality "gzip;q=0, zstd;q=0.2" "gzip") 0))
  (ok (= (woo.compat::encoding-quality "gzip;q=0, *;q=1" "gzip") 0))
  (ok (= (woo.compat::encoding-quality "gzip;q=#.(error 1)" "gzip") 0))
  (dolist (algorithm '("gzip" "zstd"))
    (let* ((e (env)) (chunks nil) (headers nil)
           (app (lack:builder :woo-deflater
                  (lambda (env) (declare (ignore env))
                    (lambda (respond)
                      (let ((writer (funcall respond '(200 (:content-type "text/plain" :content-length 999)))))
                        (funcall writer "こんにちは λ") (funcall writer nil :close t)))))))
      (setf (gethash "accept-encoding" (getf e :headers)) algorithm)
      (funcall (funcall app e)
               (lambda (res)
                 (setf headers (second res))
                 (lambda (data &key (start 0) end close)
                   (declare (ignore close))
                   (when data (push (subseq data start end) chunks)) t)))
      (ok (null (getf headers :content-length)))
      (ok (equal (getf headers :content-encoding) algorithm))
      (let* ((bytes (apply #'concatenate '(vector (unsigned-byte 8)) (nreverse chunks)))
             (plain (if (equal algorithm "gzip") (chipz:decompress nil 'chipz:gzip bytes)
                        (zstd:decompress-buffer bytes))))
        (ok (equalp plain (trivial-utf-8:string-to-utf-8-bytes "こんにちは λ")))))))

(deftest backtrace-redacts-delayed-error
  (let ((logs nil))
    (let ((app (lack:builder (:woo-backtrace :logger (lambda (e) (push e logs)))
                 (lambda (env) (declare (ignore env))
                   (lambda (respond) (declare (ignore respond)) (error "secret-token"))))))
      (funcall (funcall app (env)) (lambda (r) (ok (= (car r) 500)))))
    (ok logs) (ok (not (search "secret-token" (prin1-to-string logs))))))

(deftest session-delayed-finalization-and-cancellation
  (let* ((store (lack.session.store.memory:make-memory-store))
         (sid (make-string 40 :initial-element #\a))
         (app (lack:builder (:woo-session :store store)
                (lambda (e)
                  (incf (gethash :count (getf e :lack.session) 0))
                  (lambda (respond) (funcall respond '(200 nil ("ok")))))))
         (e (env (format nil "lack.session=~A" sid))))
    (funcall (funcall app e) #'identity)
    (ok (= (gethash :count (lack.session.store:fetch-session store sid)) 1))
    (setf (getf e :woo.request-cancelled-p) (constantly t))
    (funcall (funcall app e) #'identity)
    (ok (= (gethash :count (lack.session.store:fetch-session store sid)) 1))))

(deftest compressed-close-refusal-is-safe
  (dolist (algorithm '("gzip" "zstd"))
    (let* ((calls 0) (closed 0)
           (writer (woo.compat::compression-writer
                    (lambda (data &key start end close)
                      (declare (ignore data start end))
                      (incf calls) (when close (incf closed)) nil)
                    algorithm (env))))
      (funcall writer "fixture")
      (ok (null (funcall writer nil :close t)))
      (let ((before calls))
        (ok (null (funcall writer nil :close t)))
        (ok (= calls before)))
      (ok (zerop closed)))))
