(load "t/compat/load.lisp")
(let* ((port (parse-integer (uiop:getenv "WOO_HEGEL_PORT")))
       (nonce (uiop:getenv "WOO_HEGEL_READY_NONCE"))
       (tls-port (+ port 1))
       (cert-root (uiop:ensure-directory-pathname (or (uiop:getenv "WOO_COMPAT_CERT_ROOT") "t/certs/")))
       (auth (lack:builder
               (:auth-basic :authenticator (lambda (u p) (and (equal u "test") (equal p "test"))))
               (lambda (env) (declare (ignore env)) '(200 (:content-type "text/plain") ("authorized")))))
       (csrf (lack:builder :woo-session :csrf
               (lambda (env) (list 200 '(:content-type "text/plain")
                                   (list (lack.middleware.csrf:csrf-token (getf env :lack.session)))))))
       (session (lack:builder :woo-session
                  (lambda (env)
                    (sleep 0.001)
                    (list 200 '(:content-type "text/plain")
                          (list (write-to-string (incf (gethash :counter (getf env :lack.session) 0))))))))
       (database (dbi:connect :sqlite3 :database-name ":memory:"))
       (sqlite (lack:builder
                 (:woo-session :store (lack.session.store.dbi:make-dbi-store :connector (lambda () database)))
                 (lambda (env) (list 200 '(:content-type "text/plain")
                                    (list (write-to-string (incf (gethash :counter (getf env :lack.session) 0))))))))
       (redis (lack:builder
                (:woo-session :store (lack.session.store.redis:make-redis-store
                                       :port (parse-integer (or (uiop:getenv "WOO_COMPAT_REDIS_PORT")
                                                               (error "Redis fixture required")))
                                       :namespace nonce :expires 120))
                (lambda (env) (list 200 '(:content-type "text/plain")
                                   (list (write-to-string (incf (gethash :counter (getf env :lack.session) 0))))))))
       (pool (lack:builder
               (:dbpool :woo-compat-wire :connect-args '(:sqlite3 :database-name ":memory:")
                :pool-args '(:max-open-count 2 :max-idle-count 0 :timeout 1000))
               (lambda (env) (declare (ignore env))
                 (lack.middleware.dbpool:with-connection (conn :woo-compat-wire)
                   (list 200 '(:content-type "text/plain")
                         (list (write-to-string (getf (dbi:fetch (dbi:execute (dbi:prepare conn "SELECT 42 AS n"))) :|n|))))))))
       (initialized (dbi:do-sql database "CREATE TABLE sessions (id TEXT PRIMARY KEY, session_data TEXT)"))
       ;; The plain listener can accept the readiness probe before the
       ;; shutdown callback has been installed. Keep readiness false until
       ;; both listeners and the drain trigger are complete.
       (shutdown nil) (ready nil)
       (app
         (lack:builder :woo-backtrace :woo-deflater
           (:static :path "/static/" :root #p"t/compat/")
           (:woo-mount "/mount" (lambda (env) (list 200 '(:content-type "text/plain")
                                                   (list (format nil "~A|~A" (getf env :script-name) (getf env :path-info))))))
           (lambda (env)
             (let ((path (getf env :path-info)))
               (cond
                 ((equal path "/.woo-test-ready")
                  (if ready
                      (list 200 '(:content-type "text/plain") (list nonce))
                      (list 503 '(:content-type "text/plain") (list "starting"))))
                 ((equal path "/env")
                  (list 200 '(:content-type "text/plain")
                        (list (format nil "~A|~A|~A|~A" (getf env :url-scheme) (getf env :server-name)
                                      (getf env :path-info) (getf env :query-string)))))
                 ((equal path "/env-port")
                  (list 200 '(:content-type "text/plain") (list (write-to-string (getf env :server-port)))))
                 ((equal path "/session") (funcall session env))
                 ((equal path "/sqlite") (funcall sqlite env))
                 ((equal path "/redis") (funcall redis env))
                 ((equal path "/db") (funcall pool env))
                 ((equal path "/file") (list 200 '(:content-type "text/plain") #p"t/compat/fixture.txt"))
                 ((equal path "/metrics")
                  (let ((server (woo.compat::mr-server (getf env :woo.request))))
                    (bt2:with-lock-held ((woo.compat::ms-lock server))
                      (list 200 '(:content-type "text/plain")
                            (list (format nil "~D|~D|~D" (woo.compat::ms-input-bytes server)
                                          (woo.compat::ms-output-bytes server)
                                          (hash-table-count (woo.compat::ms-requests server))))))))
                 ((uiop:string-prefix-p "/status/" path)
                  (list (parse-integer path :start 8) nil nil))
                 ((equal path "/auth") (funcall auth env))
                 ((equal path "/csrf") (funcall csrf env))
                 ((equal path "/ws")
                  (let ((ws (websocket-driver:make-server env)))
                    (websocket-driver:on :message ws (lambda (message) (websocket-driver:send ws message)))
                    (lambda (respond) (declare (ignore respond))
                      (woo.compat:call-on-connection (getf env :clack.io)
                        (lambda () (websocket-driver:start-connection ws))))))
                 ((equal path "/drain")
                  (funcall shutdown)
                  '(200 (:content-type "text/plain") ("draining")))
                 ((equal path "/drain-slow")
                  (lambda (respond)
                    (let ((writer (funcall respond '(200 (:content-type "text/plain")))))
                      (funcall writer "before") (sleep 1)
                      (funcall writer "after" :close t))))
                 ((equal path "/broken-stream")
                  (lambda (respond)
                    (funcall (funcall respond '(200 (:content-type "text/plain"))) "partial")
                    (error "Fixture producer failure")))
                 ((equal path "/budget")
                  (lambda (respond)
                    (funcall (funcall respond '(200 (:content-type "application/octet-stream")))
                             (make-array 65537 :element-type '(unsigned-byte 8) :initial-element 42) :close t)))
                 ((equal path "/large")
                  (list 200 '(:content-type "application/octet-stream")
                        (make-array (* 10 1024 1024) :element-type '(unsigned-byte 8) :initial-element 42)))
                 ((equal path "/slow") (sleep 0.05) '(200 (:content-type "text/plain") ("ok")))
                 (t (woo.compat.tests::contract-app env)))))))
       (plain nil) (tls nil))
  (unwind-protect
       (progn
         (setf tls (woo.compat:clackup app :address "127.0.0.1" :port tls-port
                                     :max-response-queue-bytes 65536 :max-request-body-bytes 131072
                                     :ssl-key-file (merge-pathnames "localhost.key" cert-root)
                                     :ssl-cert-file (merge-pathnames "localhost.crt" cert-root)))
         (setf plain (woo.compat:clackup app :address "127.0.0.1" :port port
                                       :max-response-queue-bytes 65536 :max-request-body-bytes 131072))
         (setf shutdown (lambda ()
                          (dolist (handler (list plain tls))
                            (let ((owned handler))
                              (bt2:make-thread (lambda () (sleep 0.05) (clack:stop owned))
                                               :name "Woo fixture shutdown")))))
         (setf ready t)
         (loop (sleep 1)))
    (when plain (clack:stop plain)) (when tls (clack:stop tls)) (dbi:disconnect database)))
