(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(push #P"<HOME>/projects/woo-pr-series/09-h2-codecs/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/09-h2-codecs/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/09-h2-codecs/woo-test.asd")
(ql:quickload "woo-test" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/09-h2-codecs/")))
(unless (every #'identity (list (rove:run-suite :woo-test.hpack) (rove:run-suite :woo-test.http2-frames))) (uiop:quit 1))
(uiop:quit 0)
