(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(push #P"<HOME>/projects/woo-pr-series/05-http1-responses/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/05-http1-responses/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/05-http1-responses/woo-test.asd")
(ql:quickload "woo-test" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/05-http1-responses/")))
(unless (rove:run "woo-test") (uiop:quit 1))
(uiop:quit 0)
