(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(push #P"<HOME>/projects/woo-pr-series/02-small-fixes/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/02-small-fixes/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/02-small-fixes/woo-test.asd")
(ql:quickload "woo-test" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/02-small-fixes/")))
(unless (every #'identity (list (rove:run-suite :woo-test.file-size) (rove:run-suite :woo-test.worker) (rove:run-suite :woo-test.response))) (uiop:quit 1))
(uiop:quit 0)
