(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(push #P"<HOME>/projects/woo-pr-series/12-websocket/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/12-websocket/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/12-websocket/woo-test.asd")
(ql:quickload "woo-test" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/12-websocket/")))
(unless (every #'identity (list (rove:run-suite :woo-test.websocket) (rove:run-suite :woo-test.websocket-e2e) (rove:run-suite :woo-test))) (uiop:quit 1))
(uiop:quit 0)
