(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(pushnew :woo-no-ssl *features*)
(push #P"<HOME>/projects/woo-pr-series/10-h2-engine/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/10-h2-engine/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/10-h2-engine/woo-test.asd")
(ql:quickload "woo-test" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/10-h2-engine/")))
(uiop:quit 0)
