(load "<HOME>/quicklisp/setup.lisp")
(ql:quickload :cffi :silent t)
(dolist (d (list #P"<HOME>/.local/Homebrew/lib/" #P"<HOME>/.nix-profile/lib/")) (pushnew d cffi:*foreign-library-directories* :test #'equal))
(push #P"<HOME>/projects/woo-pr-series/13-managed-clack/" asdf:*central-registry*)
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/13-managed-clack/woo.asd")
(asdf:load-asd #P"<HOME>/projects/woo-pr-series/13-managed-clack/woo-lack-compat.asd")
(ql:quickload "woo-lack-compat/tests" :silent t)
(assert (equal (truename (asdf:system-source-directory (asdf:find-system "woo"))) (truename #P"<HOME>/projects/woo-pr-series/13-managed-clack/")))
(unless (rove:run "woo-lack-compat/tests") (uiop:quit 1))
(uiop:quit 0)
